### ISSUE TITLE
Uncaught TypeError: Cannot read property '/Users/immanuelsun/Sites/design/widget_corp/' of undefined

### ISSUE THREAD

**Issue by immanuelsun** [leny/atom-tree-ignore#20]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11.2
**Thrown From**: [tree-ignore](https://github.com/leny/atom-tree-ignore) package, v0.6.1
### Stack Trace

Uncaught TypeError: Cannot read property '/Users/immanuelsun/Sites/design/widget_corp/' of undefined

```
At /Users/immanuelsun/.atom/packages/tree-ignore/lib/tree-ignore.js:157

TypeError: Cannot read property '/Users/immanuelsun/Sites/design/widget_corp/' of undefined
    at _fHandleIgnoreFile (/Users/immanuelsun/.atom/packages/tree-ignore/lib/tree-ignore.js:157:40)
    at HTMLSpanElement.<anonymous> (/Users/immanuelsun/.atom/packages/tree-ignore/lib/tree-ignore.js:106:31)
    at Function.jQuery.extend.each (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:374:23)
    at [object Object].jQuery.fn.jQuery.each (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:139:17)
    at _fUpdate (/Users/immanuelsun/.atom/packages/tree-ignore/lib/tree-ignore.js:92:46)
    at _fApply (/Users/immanuelsun/.atom/packages/tree-ignore/lib/tree-ignore.js:72:5)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -2:19.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:17.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:17.1.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -2:14.3.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -1:48.7.0 editor:duplicate-lines (atom-text-editor.editor.is-focused)
     -1:46 core:undo (atom-text-editor.editor.is-focused)
     -1:43.8.0 application:new-window (atom-text-editor.editor.is-focused)
     -1:27.2.0 terminal-plus:toggle (atom-text-editor.editor.is-focused)
  2x -0:26.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:22.6.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:22.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:20.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:08.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:03.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:02.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.4.0 tree-ignore:enable (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "angularjs",
      "genesis-snippets",
      "meteor-api",
      "Docksend",
      "aligner-php",
      "atom-jade",
      "atom-wordpress",
      "autocomplete-php",
      "autocomplete-wordpress-hooks",
      "emmet-snippets-compatibility",
      "livereload",
      "wordpress",
      "wordpress-api",
      "atom-terminal",
      "linter-phpcs",
      "linter-tidy",
      "linter-phpmd",
      "linter-scss-lint",
      "linter",
      "linter-php"
    ],
    "projectHome": "/Users/immanuelsun/Sites/design",
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "tree-ignore": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.21
autocomplete-plus, v2.26.0
autocomplete-snippets, v1.9.0
comment-down, v0.1.1
docblockr, v0.7.3
emmet, v2.4.1
file-icons, v1.6.14
highlight-line, v0.11.0
language-gitignore, v0.2.0
language-marko, v0.4.18
linter-csslint, v1.2.0
linter-htmlhint, v1.0.2
linter-js-yaml, v1.2.5
linter-jshint, v1.2.2
linter-less, v2.3.3
linter-write-good, v0.6.1
minimap, v4.19.0
php-cs-fixer, v2.5.2
pigments, v0.22.1
project-manager, v2.7.5
seti-syntax, v0.4.1
seti-ui, v0.8.1
terminal-plus, v0.14.5
tree-ignore, v0.6.1

# Dev
No dev packages
```

**Comment by dhershman1** [comment]
Yep I'm getting this same issue on my projects as well when trying to enable it.
