### ISSUE TITLE
Uncaught TypeError: Cannot read property '/Users/tomi/Documents/Programming/Github/Eis/' of undef...

### ISSUE THREAD

**Issue by tomitrescak** [leny/atom-tree-ignore#26]
[Enter steps to reproduce below:]
1. I installed the package
2. Added .atomignore file
3. Added `.git/` into file
4. Enabled plugin

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [tree-ignore](https://github.com/leny/atom-tree-ignore) package, v0.6.1
### Stack Trace

Uncaught TypeError: Cannot read property '/Users/tomi/Documents/Programming/Github/Eis/' of undefined

```
At /Users/tomi/.atom/packages/tree-ignore/lib/tree-ignore.js:157

TypeError: Cannot read property '/Users/tomi/Documents/Programming/Github/Eis/' of undefined
    at _fHandleIgnoreFile (/Users/tomi/.atom/packages/tree-ignore/lib/tree-ignore.js:157:40)
    at HTMLSpanElement.<anonymous> (/Users/tomi/.atom/packages/tree-ignore/lib/tree-ignore.js:106:31)
    at Function.jQuery.extend.each (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:374:23)
    at [object Object].jQuery.fn.jQuery.each (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:139:17)
    at _fUpdate (/Users/tomi/.atom/packages/tree-ignore/lib/tree-ignore.js:92:46)
    at _fApply (/Users/tomi/.atom/packages/tree-ignore/lib/tree-ignore.js:72:5)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -1:17.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:14.7.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:11.3.0 core:copy (atom-text-editor.editor.is-focused)
     -1:09.6.0 core:paste (atom-text-editor.editor.is-focused)
     -1:08.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:52.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:17 tree-view:add-file (div.header.list-item)
     -0:15.9.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:14.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.2.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:06.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:05.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 tree-ignore:enable (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "language-gfm",
      "language-babel"
    ],
    "ignoredNames": [
      "node_modules"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.7
atom-chai-snippets, v0.3.0
atom-html-preview, v0.1.19
atom-macros, v0.5.2
atom-typescript, v8.10.1
atom-wallaby, v1.0.7
autoclose-html, v0.23.0
docblockr, v0.7.3
file-icons, v1.7.11
language-markdown, v0.13.0
linter, v1.11.4
linter-eslint, v7.2.2
linter-tslint, v0.9.3
merge-conflicts, v1.4.2
minimap, v4.23.5
minimap-linter, v1.1.1
permanent-delete, v0.1.5
react, v0.15.0
tree-ignore, v0.6.1
zentabs, v0.8.7

# Dev
No dev packages
```

**Comment by jacquescrocker** [comment]
I'm also seeing this error in latest atom

**Comment by jacquescrocker** [comment]
solution is possibly here:  #29
